#!/usr/bin/env ruby
# frozen_string_literal: true

# vim:sta:et:sw=2:ts=2:syntax=ruby
# -*- Mode: Ruby; tab-width: 2; indent-tabs-mode: nil -*-

require 'bundler/setup'
require 'pacwrap/cli'

begin
  Pacwrap::CLI.start
rescue RuntimeError => e
  warn "ERROR: #{e.message}"
end
